### ISSUE TITLE
Images for README

### ISSUE THREAD

**Issue by cola4cube** [cola4cube/beamer-theme-tub#1]
![titlepage](https://cloud.githubusercontent.com/assets/15649114/11145090/7fc732ae-8a02-11e5-8189-2427b74939d1.png)
![example-page2](https://cloud.githubusercontent.com/assets/15649114/11145092/86abd46c-8a02-11e5-829f-3479eb6bb453.png)

**Comment by frodo4fingers** [comment]
öhhh.. wo ist jetzt genau das problem?

**Comment by cola4cube** [comment]
???

Der Issue ist nur für die Bilder da. Es gibt sonst bei Github keine Möglichkeit Bilder für die Readme hoch zu laden. Man müsste sie sonst extern irgendwo hosten 

Am 13.11.2015 2:22 nachm. schrieb frodo4fingers notifications@github.com:

öhhh.. wo ist jetzt genau das problem?
