### ISSUE TITLE
Undefined control sequence: \preslocation

### ISSUE THREAD

**Issue by bonh** [cola4cube/beamer-theme-tub#2]
## Minimal working example:

\documentclass{beamer}
\usetheme{TUBlayout}

\title{Sample title}
\author{Anonymous}
\institute{Bla}
\date{2016}

\begin{document}
\frame{\titlepage}
## \end{document}

pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015/Arch Linux)

**Comment by bonh** [comment]
Nevertheless, the theme is great, thank you!

**Comment by cola4cube** [comment]
Thanks!
As mentioned in the example, there is a new variable \preslocation which is defined before 
\begin{document}. This variable is needed for the titlepage to insert the occasion of the presentation (e.g. the location where the presentation is held)

``` latex
\newcommand{\preslocation}{Location where presentation is held}
```
